from enum import StrEnum


class EventType(StrEnum):
    TASK_SUBMITTED = "TASK_SUBMITTED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TOOL_INVOKED = "TOOL_INVOKED"
    TOOL_COMPLETED = "TOOL_COMPLETED"
    TOOL_FAILED = "TOOL_FAILED"
    STATE_CHANGED = "STATE_CHANGED"
    MEMORY_ACCESSED = "MEMORY_ACCESSED"
    RETRY_ATTEMPTED = "RETRY_ATTEMPTED"
    ERROR_OCCURRED = "ERROR_OCCURRED"

